### ISSUE TITLE
If I rotate, can I save the rotated version?

### ISSUE THREAD

**Issue by moneytree-doug** [bcabanes/angular-image-cropper#10]
It looks like it's just using CSS to rotate, is it possible to save it's mutated state?

**Comment by annmirosh** [comment]
Hi!  I'm not the author but let me answer on your question. Yes, you can save the rotated version of the image. I used this component in my app and the rotated image was saved fine.

**Comment by bcabanes** [comment]
Hi @moneytree-doug,
Yes! As @annmirosh said, you can. May be you can explain more your problem?

**Comment by bcabanes** [comment]
Seems resolved. Closing.
