### ISSUE TITLE
crossOrigin header for cross origin images (e.g. AmazonS3)

### ISSUE THREAD

**Issue by jamiemcl** [bcabanes/angular-image-cropper#14]
Hi,

I'm just wondering if it would be at all possible for you to allow the cropper to work with cross origin images at all? Currently, I get the following error when trying to access an image stored in amazons3:

Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

I have made sure that the I have given my amazons3 bucket the required CORS rule to allow for cross origin images, however, the directive still does not work with these types of image.

Is there anything that could be done here?

Thanks

**Comment by Zyst** [comment]
I also started having this issue. 

It used to work a bit ago, not sure how I can fix it.

@jamiemcl to configure S3 to allow CORS with Chrome check this out: http://erick-romero.com/how-to-fix-aws-s3-chrome-and-safari-cors-on-images/

**Comment by bcabanes** [comment]
@Zyst Yes this is it,
There is also this thread on stackoverflow.com about this: http://stackoverflow.com/questions/12947361/cors-settings-for-images-in-canvas

Also, i'm preparing a new version with better crossOrigin support.

Closing.

**Comment by pavelboksha** [comment]
Hi, bcabanes 
Best cropper for angular I ever seen.... But CORS!!!! I have images on another server, so get Image but can't use crop button or API.
