### ISSUE TITLE
JQLite not supported

### ISSUE THREAD

**Issue by vani12345** [bcabanes/angular-image-cropper#15]
Our application does not use JQuery and refers Angualrs JQlite. But the angular-image-cropper, does not work without Jquery. Can you just edit the line in the directive, where it uses angular.element('body') to angular.element(document).find('body').

This would be really great and I can use this without have to tweak it too much

Thanks

**Comment by bcabanes** [comment]
Hi @vani12345,
I'm currently working on a version working with pure javascript. No needs of jQlite or jQuery.
Hope release asap. 
:)
