### ISSUE TITLE
/dist folder is gone?

### ISSUE THREAD

**Issue by mattmazzola** [bcabanes/angular-image-cropper#17]
Hi,

I was using your project from bower and there used to be a dist folder with:
angular-image-cropper.min.css
angular-image-cropper.min.js

With the update to 1.0 these files are missing.

**Comment by bcabanes** [comment]
Hi @mattmazzola,
Yes the build seems to fail when uploading to npm i'm on it. You can require the module with fil in the src folder until then.

**Comment by bcabanes** [comment]
Ho sorry, you're using bower as package dependencies. You can install an older version:
`$ bower install ng-image-cropper#0.1.1`

**Comment by mattmazzola** [comment]
Yea, I'll use that as a work-around until the build is fixed. Thanks.

**Comment by bcabanes** [comment]
Hi @mattmazzola,
You can use this url to install the lastest version of angular-image-cropper:
```bash
$ bower install https://npmcdn.com/angular-image-cropper/bower.zip
```
I'll update the readme soon.
