### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by srobledo** [bcabanes/angular-image-cropper#18]
Hi,

I've been trying to upload an image and covert it to a base64, but when uploading another image again the cropper is not updating the image

**Comment by bcabanes** [comment]
Hi @srobledo,
Do you have a [plunkr](http://plnkr.co) or [jsbin](https://jsbin.com) to show?
Did you tried to re-instantiate the directive with a ngIf?

**Comment by eZ0** [comment]
I've had the same issue & ng-if is a good option. Thanks!

**Comment by bcabanes** [comment]
Closing as ng-if is the solution.

**Comment by sureshkoduri** [comment]
How to use ng-if in <image-cropper>??
