### ISSUE TITLE
Zoom step doesn't work properly

### ISSUE THREAD

**Issue by eZ0** [bcabanes/angular-image-cropper#20]
Hi, it seems like zoom-step doesn't work properly. I've tried changing it from 0.1 to 0.9, but it's always the same zoom. Browsers: Safari (v 9.0.3), Chrome Canary(v 50.0.2652.0), Firefox (v 43.0.4).

**Comment by bcabanes** [comment]
Hi @eZ0,
Thank you! Seems to be a bug, i'll look into this one.

**Comment by eZ0** [comment]
@bcabanes thanks a lot for a fix! Works perfectly now :unicorn_face:
