### ISSUE TITLE
Please support bower install

### ISSUE THREAD

**Issue by megha-n-bodke** [bcabanes/angular-image-cropper#23]
Please support "bower install" version support
```script
bower install angular-image-cropper
```
Currently it updates bower.json to 
```script
"angular-image-cropper": "*"
```
It should update to i.e. same as package.json
```script
"angular-image-cropper": "~1.1.5"
```

**Comment by bcabanes** [comment]
Hi @megha-n-bodke,
The bower installation has been dropped to use npm instead which is more reliable and powerful. You can still install the latest version of the package using bower by doing:
```bash
$ bower install https://npmcdn.com/angular-image-cropper/bower.zip --save
```

**Comment by brazorf** [comment]
Sorry to bump this. Why is bower usage not recommended? We all run projects that might rely on bower for other dependencies, and migrate everything to npm can't always be put on high priority.

However, why do fetch the package from cdn instead of the default bower repository? Just asking here.

**Comment by divyekhanna** [comment]
+1
