### ISSUE TITLE
Change image source

### ISSUE THREAD

**Issue by nathandace** [bcabanes/angular-image-cropper#27]
I have the directive loaded with the image url on the directive bound to a property on my controller.  

In my setup, a user can select the image to view, and I change the url source on my controller.  However, the image does not update or reinitialize when the url changes.

**Comment by alyrik** [comment]
+ the same for me. `image-url` changes its value but this doesn't affect an `img` inside directive.

**Comment by ryanmarshall** [comment]
hey @bcabanes Benjamin I'm working on using this cropper with ng-image-upload to allow custom uploads and editing if the image. It seems like loading the uploaded image into imageUrl dynamically doesn't change the image.

Wondering the priority of this fix, would really love to use this but can't right now.

**Comment by bcabanes** [comment]
Hi @ryanmarshall, 
This is on my todo list but i can't get the time to do it right now. I will look into this as soon as I can.

**Comment by sureshkoduri** [comment]
Hi,

I done like this below,

in Controller
------------------
```
$scope.fileChanged = function(event) {
    	$scope.imageURL = undefined;
    	$scope.file = event.target.files[0];
    	$scope.file.convertToBase64(function(base64){
           $scope.imageURL = base64;
           $scope.$apply(); 
        })
  	};
```
-------------
in html added simple-change directive
`<input type="file" simple-change="fileChanged($event)" accept="image/*">`

----

And its worked for me..

**Comment by chhumsina** [comment]
Hi @sureshkoduri ,

I have put your stuff, but it's error in Controler:  $scope.file.convertToBase64 (not a function)

Thanks

**Comment by sureshkoduri** [comment]
@chhumsina , Please put the below code in your app.config

```
File.prototype.convertToBase64 = function(callback){
            var reader = new FileReader();
            reader.onload = function(e) {
                 callback(e.target.result)
            };
            reader.onerror = function(e) {
                 callback(null);
            };        
            reader.readAsDataURL(this);
    };
```

**Comment by flkt-crnpio** [comment]
Hi,
This is working for me

### Controller
<pre>
$scope.imageUrl = null;
var handleFileSelect = function(evt) {
    var file = evt.currentTarget.files[0];
    var reader = new FileReader();
    reader.onload = function (evt) {
        $scope.$apply(function($scope){
            $scope.imageUrl=evt.target.result;
        });
    };
    reader.readAsDataURL(file);
};
var cleanFileSelect = function(evt) {
    $scope.imageUrl = null;
    angular.element(document.querySelector('#fileInput')).value = "";
}
angular.element(document.querySelector('#fileInput')).on('click',cleanFileSelect);
angular.element(document.querySelector('#fileInput')).on('change',handleFileSelect);
</pre>

### View
<pre>
&lt;input accept="image/*" type="file" id="fileInput"/>

&lt;image-cropper 
    image-url="{{imageUrl}}" 
    width="200" 
    height="200" 
    fit-on-init="true" 
    ng-if="imageUrl"
>
&lt;/image-cropper>
</pre>

**Comment by gmtproject** [comment]
None of them them worked for me. 

Are you planing to add image change function. 

And is it possible for someone add a plunker.

Thanks

**Comment by nickxbs** [comment]
Hi,
https://github.com/bcabanes/angular-image-cropper/pull/45 fix the bug for me.
