### ISSUE TITLE
Incorrect version 0.0.1 in bower.json

### ISSUE THREAD

**Issue by nilathj** [bcabanes/angular-image-cropper#4]
Hi,
This looks really interesting. I would love to test it out. I'm trying to download the 0.1.0 release using bower and it looks like the version released is 0.1.0 but the version declared in the json is 0.0.1.  As a result I'm not able to download it.

bower ng-image-cropper#*                   download https://github.com/bcabanes/angular-image-cropper/archive/v0.1.0.tar.gz
bower ng-image-cropper#*                    extract archive.tar.gz
bower ng-image-cropper#*                   mismatch Version declared in the json (0.0.1) is different than the resolved one (0.1.0)
bower ng-image-cropper#*                   resolved git://github.com/bcabanes/angular-image-cropper.git#0.1.0
bower angular-image-cropper#~0.1.0     ENORESTARGET No tag found that was able to satisfy ~0.1.0

In your bower.json the version is 0.0.1.

**Comment by nilathj** [comment]
sorry my bad, I was refering to angular-image-cropper rather than ng-image-cropper!.

**Comment by bcabanes** [comment]
Hi @nilathj,
Thanks for spotting this, it should be fixed now ;)
Ben
