### ISSUE TITLE
Behavior when you drag outside the box

### ISSUE THREAD

**Issue by acromm** [bcabanes/angular-image-cropper#5]
I detect this behavior and is more common if you are zoomed and the box is small (so you need to drag a lot).

When you drag outside the box the image stops moving. If you release the click doesnt really release it until you are inside the box and click-release again. Also when you go back to the box the image "jumps" to adjust the origin-dragging-point to the new mouse position inside the box.

I think one solution is avoiding to go outside the box when you are dragging (dunno if this is posible) so every time you release you are always inside.Or maybe if you reach some of the edges of the box force the release.

The other solution could be enable dragging outside the box (until some limit is reached) and enable releasing the mouse outside too.

**Comment by farskid** [comment]
Is it fixed for now?
