### ISSUE TITLE
The directive does not add required classes

### ISSUE THREAD

**Issue by farskid** [bcabanes/angular-image-cropper#6]
Exploring the directive.js file in your Dev folder of project, I have seen the directive adds classes like `imgCropper-dragging` so the css could change the style.
Unfortunately my version is not adding any classes.
What I wanted to achieve was to play around with css to make a blur version of image that is outside of canvas so that the user would see the rest of image that is not cropped. That was were I found out the classes you intended to add are not adding at all!!
Any help would be appreciated.

**Comment by FDIM** [comment]
It's a bit strange, but it adds the class to body tag.
