### ISSUE TITLE
Angular 1.4.* compatibility

### ISSUE THREAD

**Issue by pdoreau** [bcabanes/angular-image-cropper#8]
Hello,

Does this usefull module work well with angular 1.4.* ?
I'm using 1.4.7 and no controll button is displayed. What can I do ?

**Comment by FDIM** [comment]
Works alright for me

**Comment by bcabanes** [comment]
Hi @pdoreau,
This is weird, because i'm using this module with 1.5 and it works for me. Can you have a specific error?

**Comment by bcabanes** [comment]
No news. Closing.
